theme: minima
title: Stone
author: GitHub User
email: your-email@domain.com
description: > # something something or othere 

# social links
twitter_username: nothing herer 
github_username: nothing here eathier

show_excerpts: true # set to false to remove excerpts on the homepage
